     CREATE TABLE IF NOT EXISTS film_mpa (
             mpa_id           INTEGER PRIMARY KEY NOT NULL,
             mpa_name         VARCHAR(5)
          );

     CREATE TABLE IF NOT EXISTS film (
        film_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        film_name        VARCHAR(50) NOT NULL,
        release_date     DATE,
        description      varchar(200),
        duration         INTEGER,
        mpa_id           INTEGER REFERENCES film_mpa (mpa_id) ON DELETE CASCADE
    );

     CREATE TABLE IF NOT EXISTS users (
        users_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        email           VARCHAR(50) NOT NULL,
        user_login      VARCHAR(50) NOT NULL,
        birthday        DATE,
        users_name      VARCHAR(50)

     );

     CREATE TABLE IF NOT EXISTS user_like (
         user_id         INTEGER REFERENCES users (users_id) ON DELETE CASCADE,
         film_id         INTEGER REFERENCES film (film_id) ON DELETE CASCADE
     );

     CREATE TABLE IF NOT EXISTS genre (
         genre_id        INTEGER PRIMARY KEY NOT NULL,
         genre_name      VARCHAR(50)
     );

     CREATE TABLE IF NOT EXISTS film_genre (
         genre_id        INTEGER REFERENCES genre (genre_id) ON DELETE CASCADE,
         film_id         INTEGER REFERENCES film (film_id) ON DELETE CASCADE
     );

    CREATE TABLE IF NOT EXISTS user_friend (
        user_id           INTEGER REFERENCES users (users_id) ON DELETE CASCADE,
        friend_id         INTEGER REFERENCES users (users_id) ON DELETE CASCADE
    );

     CREATE UNIQUE INDEX IF NOT EXISTS USER_EMAIL_UINDEX on USERS(email);

     CREATE UNIQUE INDEX IF NOT EXISTS USER_LOGIN_UINDEX on USERS(user_login)




